name: Django CI

on:
  push:
    branches:
      - Dev-1  
  pull_request:
    branches:
      - Dev-1

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: galactic_hiker 
          POSTGRES_PASSWORD: Nebula$2024!
          POSTGRES_DB: starry_night  
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List project files
      run: ls -la

    - name: Check current directory
      run: pwd

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r customers_orders/requirements.txt  

    - name: Wait for PostgreSQL
      run: |
        for i in {30..0}; do
          if pg_isready -h localhost -p 5432 -U galactic_hiker; then 
            break
          fi
          echo 'Waiting for PostgreSQL...'
          sleep 1
        done

    - name: Set up database
      run: python manage.py migrate
      working-directory: ./customers_orders  

    - name: Run tests
      run: python manage.py test
      working-directory: ./customers_orders 
