# .github/workflows/ci.yml

name: Django CI

on:
  push:
    branches:
      - Dev-1  # Runs on the Dev-1 branch
  pull_request:
    branches:
      - Dev-1

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: starry_night
          POSTGRES_PASSWORD: galactic_hiker
          POSTGRES_DB: mydatabase
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install psycopg2  # Add PostgreSQL driver

    - name: Set up database
      run: python manage.py migrate

    - name: Run tests
      run: python manage.py test
